// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzTkiEkmAnHw11a4dcl66xb_mdCqVvLY',
    appId: '1:584073020996:web:61a3ca5a301e35b0b75e11',
    messagingSenderId: '584073020996',
    projectId: 'ecommerce-ce5dd',
    authDomain: 'ecommerce-ce5dd.firebaseapp.com',
    storageBucket: 'ecommerce-ce5dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmTvHyfl1MMilSLB8OqY3J6wo6S0pGUw',
    appId: '1:584073020996:android:3ebc93e0266dcafbb75e11',
    messagingSenderId: '584073020996',
    projectId: 'ecommerce-ce5dd',
    storageBucket: 'ecommerce-ce5dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYptW3x-fW35RhHID7zbKK_EeOcCOOptA',
    appId: '1:584073020996:ios:c0ba6aec1a34cf30b75e11',
    messagingSenderId: '584073020996',
    projectId: 'ecommerce-ce5dd',
    storageBucket: 'ecommerce-ce5dd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYptW3x-fW35RhHID7zbKK_EeOcCOOptA',
    appId: '1:584073020996:ios:c0ba6aec1a34cf30b75e11',
    messagingSenderId: '584073020996',
    projectId: 'ecommerce-ce5dd',
    storageBucket: 'ecommerce-ce5dd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrzTkiEkmAnHw11a4dcl66xb_mdCqVvLY',
    appId: '1:584073020996:web:554c35ab1c7e65d2b75e11',
    messagingSenderId: '584073020996',
    projectId: 'ecommerce-ce5dd',
    authDomain: 'ecommerce-ce5dd.firebaseapp.com',
    storageBucket: 'ecommerce-ce5dd.firebasestorage.app',
  );

}